dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    secure: R+bATkbJq3LIbfw5AaZHHfV2FZg4V1A07olpfnsO7QKEYIs04VKOY5DCglQUCu9QzKRGbglsBMAeutC4VyRFTixPJtdVkSnNcAT74Ylz3GDDWTUOY68yRax+GDL5fZ1H7zEIiRCGoJkxbgXhMz5Rnb7JWu8GqlVv7/ENnCnGPFdPiBBegIoh3KZGnuI6pNCRAgo61ukro8EzzAh1EhCNWo8LVeWlr3693YkzjEXEzeAGeg2338wRjVKZCw4KKO5o8AaSRG9Vy7pzVl1+c7bC/A0Jr7DYo4F5AQVSa7baQqMeVQys+Rh76JYY8hZ5pNysAEIzFJaaqjpk2bOnW6ohxn5C+rH88ah5zEqbaq8AdN4wjj9AmKzgytnc7m26cqZNCVcwV9WNdHz1Vk6OmXjtVvXdCNtDM92l3uHOeZykQSqGCdbRKHcvHuVu1pLod45skzjdZ1ylhHy2BGZeu57/LJKxHdZZjYRm2rU359Bg2yekEpdu2W+L/MCXOg5Gkbw9u5R0Jk4Zx4G4yGowKU7IqKg5pi28Y5H+mD90UqGCsFboKi17/ziHpx0vOeFD2/M95YjYOiu87iSHNDvLtlljxdbydzMS1jiBLhD1DiBkMYiugSlUQ8nauELZl5SuSYcxo23SamtVM37oh280YG6yPhGzbcgYdjTM2BL4eRjo2Bg=
